/*
 * File: app/store/CustomerStore.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.store.CustomerStore', {
    extend: 'Ext.data.Store',
    alias: 'store.customerstore',

    requires: [
        'FiltroMat.model.Customer',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'FiltroMat.model.Customer',
        storeId: 'CustomerStore',
        proxy: {
            type: 'ajax',
            url: 'http://filtromat-filtromat.rhcloud.com/rest/customers',
            reader: {
                type: 'json',
                rootProperty: 'customers'
            }
        }
    }
});