/*
 * File: app/store/MyStore.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.store.MyStore', {
    extend: 'Ext.data.Store',

    requires: [
        'FiltroMat.model.Product'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                key: '12312312321313',
                name: 'Jessie Morgan',
                description: 'Cuit 1',
                currentPrice: '100'
            }
        ],
        model: 'FiltroMat.model.Product',
        storeId: 'MyStore'
    }
});