/*
 * File: app/view/CustomerDetail.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.view.CustomerDetail', {
    extend: 'Ext.Panel',
    alias: 'widget.customerdetail',

    requires: [
        'Ext.Panel',
        'Ext.XTemplate',
        'Ext.Button'
    ],

    config: {
        itemId: 'customerDetail',
        id: 'customerDetail',
        layout: 'vbox',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'panel',
                itemId: 'customerDetailPanel',
                tpl: [
                    '<div id="customerDetail" class="detail">',
                    '    <h3> {name} </h3>',
                    '    ',
                    '    <dl>        ',
                    '        <dt> Razón Social </dt>',
                    '        <dd> {corporateName} </dd>',
                    '        ',
                    '        <dt> CUIT </dt>',
                    '        <dd> {cuit} </dd>',
                    '        ',
                    '        <dt> Correo </dt>',
                    '        <dd> {email} </dd>',
                    '        ',
                    '        <dt> Teléfono </dt>',
                    '        <dd> {phone} </dd>',
                    '        ',
                    '        <dt> Domicilio </dt>',
                    '        <dd> {address} </dd>',
                    '    </dl>',
                    '</div>'
                ]
            }
        ],
        listeners: [
            {
                fn: 'onPanelUpdatedata',
                event: 'updatedata'
            }
        ]
    },

    onPanelUpdatedata: function(component, newData, eOpts) {
        var details = this.down('#customerDetailPanel');
        details.setData(newData);
    }

});