/*
 * File: app/view/MainTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.view.MainTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.maintabpanel',

    requires: [
        'FiltroMat.view.CustomersNav',
        'FiltroMat.view.ProductsNav',
        'FiltroMat.view.OrdersNav',
        'Ext.navigation.View',
        'Ext.form.Panel',
        'Ext.dataview.List',
        'Ext.tab.Bar'
    ],

    config: {
        items: [
            {
                xtype: 'customersnav',
                title: 'Clientes',
                iconCls: 'user'
            },
            {
                xtype: 'ordersnav',
                title: 'Pedidos',
                iconCls: 'organize'
            },
            {
                xtype: 'productsnav',
                title: 'Productos',
                iconCls: 'more'
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        activeItem: 1
    }

});