/*
 * File: app/view/NewCustomer.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.view.NewCustomer', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newcustomer',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.Button'
    ],

    config: {
        id: 'newCustomerForm',
        items: [
            {
                xtype: 'fieldset',
                centered: false,
                id: 'newCustomerFieldset',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'name',
                        label: 'Nombre',
                        name: 'name',
                        placeHolder: 'Ingrese el nombre'
                    },
                    {
                        xtype: 'textfield',
                        id: 'razonSocialTxtField',
                        label: 'R. Social',
                        labelWrap: true,
                        name: 'corporateName',
                        placeHolder: 'Ingrese el nombre'
                    },
                    {
                        xtype: 'textfield',
                        id: 'cuitTxtField',
                        label: 'CUIT',
                        name: 'cuit',
                        placeHolder: 'Ingrese el CUIT'
                    },
                    {
                        xtype: 'emailfield',
                        id: 'emailTxtField',
                        label: 'Correo',
                        name: 'email',
                        placeHolder: 'correo@ejemplo.com'
                    },
                    {
                        xtype: 'textfield',
                        id: 'telefonoTxtField',
                        label: 'Tel',
                        name: 'phone',
                        placeHolder: 'Ingrese el teléfono'
                    },
                    {
                        xtype: 'textfield',
                        id: 'domicilioTxtField',
                        label: 'Domicilio',
                        name: 'address',
                        placeHolder: 'Ingrese el domicilio'
                    }
                ]
            },
            {
                xtype: 'button',
                id: 'saveCustomerBtn',
                margin: '20px 0px 5px 0px',
                ui: 'confirm',
                text: 'Guardar'
            },
            {
                id: 'deleteCustomerBtn',
                xtype: 'button',
                margin: '0px 0px 0px',
                ui: 'decline',
                text: 'Eliminar'
            }
        ]
    },
    
    show: function() {
      // Oculto el btn de eliminar si está creando un cliente nuevo
      if (this.getRecord() == null) {
        Ext.getCmp('deleteCustomerBtn').hide();
      } else {
        Ext.getCmp('deleteCustomerBtn').show();
      }
      this.callParent();
    }

});