/*
 * File: app/view/NewCustomer.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.view.NewCustomer', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newcustomer',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.Button'
    ],

    config: {
        id: 'newcustomer',
        items: [
            {
                xtype: 'fieldset',
                centered: false,
                items: [
                    {
                        xtype: 'textfield',
                        id: 'nombreTxtField',
                        label: 'Nombre',
                        placeHolder: 'Ingrese el nombre'
                    },
                    {
                        xtype: 'textfield',
                        id: 'razonSocialTxtField',
                        label: 'R. Social',
                        labelWrap: true,
                        placeHolder: 'Ingrese el nombre'
                    },
                    {
                        xtype: 'textfield',
                        id: 'cuitTxtField',
                        label: 'CUIT',
                        placeHolder: 'Ingrese el CUIT'
                    },
                    {
                        xtype: 'emailfield',
                        id: 'emailTxtField',
                        label: 'Correo',
                        placeHolder: 'correo@ejemplo.com'
                    },
                    {
                        xtype: 'textfield',
                        id: 'telefonoTxtField',
                        label: 'Tel',
                        placeHolder: 'Ingrese el teléfono'
                    },
                    {
                        xtype: 'textfield',
                        id: 'domicilioTxtField',
                        label: 'Domicilio',
                        placeHolder: 'Ingrese el domicilio'
                    }
                ]
            },
            {
                xtype: 'button',
                margin: 20,
                ui: 'confirm',
                text: 'Guardar'
            }
        ]
    }

});