/*
 * File: app/view/NewOrder.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.view.NewOrder', {
    extend: 'Ext.form.Panel',
    alias: 'widget.neworder',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Number'
    ],

    config: {
        id: 'newOrderForm',
        showAnimation: '',
        title: 'Nuevo Pedido',
        items: [
            {
                xtype: 'button',
                id: 'saveOrderBtn',
                margin: '20px 0px 0px',
                ui: 'confirm',
                text: 'Guardar'
            },
            {
                xtype: 'fieldset',
                centered: false,
                docked: 'top',
                items: [
                
                    {
                        xtype: 'searchfield',
                        id: 'newOrderCustomerTxt',
                        label: 'Cliente',
                        placeHolder: 'Busque un cliente'
                    },
                    
                    {
                        xtype: 'list',
                        id: 'orderCustomersList',
                        cls: "x-simulator-popup",
                        hidden: true,
                        styleHtmlContent: true,
                        onItemDisclosure: false,
                        height: '100px',
                        width: "100%",
                        height: '100px',
                        emptyText: 'Ningún cliente coincide con el filtro',
                        store: 'CustomerStore',
                        itemTpl: [
                            '<div> {name} </div>'
                        ],
                        
                        // CUSTOM
                        idFromRecord: null, // id del cliente seleccionado
                        autoCompleteTxtField: null, // referencia al autocomplete
                    },
                    
                    {
                        xtype: 'searchfield',
                        id: 'newOrderProductTxt',
                        label: 'Producto',
                        placeHolder: 'Busque un producto'
                    },
                    
                    {
                        xtype: 'list',
                        id: 'orderProductsList',
                        cls: "x-simulator-popup",
                        hidden: true,
                        styleHtmlContent: true,
                        onItemDisclosure: false,
                        height: '100px',
                        width: "100%",
                        height: '100px',
                        emptyText: 'Ningún producto coincide con el filtro',
                        store: 'ProductStore',
                        itemTpl: [
                            '<div> {name} </div>'
                        ],
                        
                        // CUSTOM
                        idFromRecord: null, // id del producto seleccionado
                        autoCompleteTxtField: null, // referencia al autocomplete
                    },
                    
                    {
                        xtype: 'numberfield',
                        id: 'orderQuantityTxt',
                        label: 'Cantidad',
                        labelWrap: true
                    }
                ]
            },
        ]
    },
    
    show: function() {
      var firstProduct = Ext.getStore('ProductStore').getAt(0);
      Ext.getCmp('newOrderProductTxt').setValue(firstProduct.data.name);
      Ext.getCmp('newOrderProductTxt').idFromRecord = firstProduct.data.key;
      this.callParent();
    }

});