/*
 * File: app/view/NewOrder.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.view.NewOrder', {
    extend: 'Ext.form.Panel',
    alias: 'widget.neworder',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Number'
    ],

    config: {
        showAnimation: '',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Nuevo Pedido'
            },
            {
                xtype: 'button',
                margin: 20,
                ui: 'confirm',
                text: 'Guardar'
            },
            {
                xtype: 'fieldset',
                centered: false,
                docked: 'top',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'nombreTxtField1',
                        label: 'Cliente'
                    },
                    {
                        xtype: 'numberfield',
                        id: 'razonSocialTxtField1',
                        label: 'Cantidad',
                        labelWrap: true
                    }
                ]
            }
        ]
    }

});