/*
 * File: app/view/NewProduct.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.view.NewProduct', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newproduct',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.TextArea',
        'Ext.Button'
    ],

    config: {
        itemId: 'newProductForm',
        items: [
            {
                xtype: 'fieldset',
                centered: false,
                id: 'newProductFieldset',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'productName',
                        label: 'Nombre',
                        name: 'name',
                        placeHolder: 'Ingrese el nombre'
                    },
                    {
                        xtype: 'textareafield',
                        id: 'productDescription',
                        label: 'Descr.',
                        labelWrap: true,
                        name: 'description'
                    },
                    {
                        xtype: 'textfield',
                        id: 'productPrice',
                        label: 'Precio',
                        name: 'currentPrice',
                        placeHolder: 'Precio actual'
                    }
                ]
            },
            {
                xtype: 'button',
                id: 'saveProductBtn',
                margin: '20px 0px 5px 0px',
                ui: 'confirm',
                text: 'Guardar'
            },
            {
                id: 'deleteProductBtn',
                xtype: 'button',
                margin: '0px 0px 0px',
                ui: 'decline',
                text: 'Eliminar'
            }
            
        ]
    },
    
    show: function() {
      // Oculto el btn de eliminar si está creando un producto nuevo
      if (this.getRecord() == null) {
        Ext.getCmp('deleteProductBtn').hide();
      } else {
        Ext.getCmp('deleteProductBtn').show();
      }
      this.callParent();
    }

});