/*
 * File: app/view/ProductsContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.view.ProductsContainer', {
    extend: 'Ext.Container',
    alias: 'widget.productscontainer',

    requires: [
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'productsList',
        layout: 'vbox',
        items: [
            {
                xtype: 'searchfield',
                id: 'searchProduct',
                itemId: 'mysearchfield',
                styleHtmlContent: true,
                placeHolder: 'Buscar Producto'
            },
            {
                xtype: 'list',
                flex: 1,
                id: 'productsList',
                disableSelection: true,
                emptyText: 'No hay productos para mostrar',
                itemTpl: [
                    '<div> {name} </div>'
                ],
                loadingText: 'Cargando...',
                store: 'ProductStore',
                grouped: false,
                onItemDisclosure: true
            }
        ]
    }

});