/*
 * File: app/view/CustomersNav.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.view.ProductsNav', {
    extend: 'Ext.navigation.View',
    alias: 'widget.productsnav',

    requires: [
        'FiltroMat.view.ProductsContainer',
        'Ext.navigation.Bar'
    ],

    config: {
        id: 'productsNav',
        itemId: 'productsNav',
        defaultBackButtonText: 'Productos',
        useTitleForBackButtonText: true,
        navigationBar: {
            items: [
                {
                    xtype: 'button',
                    iconCls: 'add',
                    align: 'right',
                    itemId: 'newProductBtn',
                    id: 'newProductBtn',
                    text: ''
                },
                {
                    xtype: 'button',
                    align: 'right',
                    id: 'editProductBtn',
                    text: 'Editar',
                    hidden: true
                }
            ],
            centered: false,
            docked: 'top'
        },
        items: [
            {
                xtype: 'productscontainer',
                title: 'Productos'
            }
        ]
    }

});