/*
 * File: app/model/Customer.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.model.Customer', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Rest',
        'Ext.data.writer.Json'
    ],

    config: {
        idProperty: 'key',
        fields: [
            {
                name: 'key',
                type: 'auto'
            },
            {
                name: 'name',
                type: 'string'
            },
            {
                name: 'corporateName',
                type: 'string'
            },
            {
                name: 'cuit',
                type: 'string'
            },
            {
                name: 'email',
                type: 'string'
            },
            {
                name: 'phone',
                type: 'string'
            },
            {
                name: 'address',
                type: 'string'
            }
        ],
        validations: [
            { type: 'presence', field: 'name' },
            { type: 'format', field: 'email', matcher: /(^$|^.*@.*\..*$)/ },
            { type: 'format', field: 'cuit', matcher: /(^$|^[\d]{2}-[\d]{7,8}-[\d]$)/ },
        ],
        proxy: {
            type: 'rest',
            url: FiltroMat.utils.Config.getApiUrl() + 'customers',
            headers: {
              'Accept': 'application/json',
              'Authorization': FiltroMat.utils.Config.getAuthorizationToken()
            },
            writer: {
                type: 'json'
            }
        }
    }
});