/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Ext.MessageBox',
        'Ext.data.identifier.Uuid',
        'FiltroMat.utils.Config'
    ],
    models: [
        'Customer',
        'Product',
        'Order',
        'Transaction'
    ],
    stores: [
        'CustomerStore',
        'ProductStore',
        'OrderStore',
        'TransactionStore'
    ],
    views: [
        'MainTabPanel',
        'CustomersContainer',
        'NewCustomer',
        'CustomersNav',
        'CustomerDetail',
        'OrdersContainer',
        'OrderDetail',
        'NewOrder',
        'ProductsContainer',
        'NewProduct'
        
    ],
    controllers: [
        'Customers',
        'Products',
        'Orders'
    ],
  	path: {
  		'Ext.ux': 'libs/ux'
  	},
    name: 'FiltroMat',

    launch: function() {

        Ext.create('FiltroMat.view.MainTabPanel', {fullscreen: true});
    }

});
