/*
 * File: app/controller/Customers.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FiltroMat.controller.Customers', {
    extend: 'Ext.app.Controller',
    alias: 'controller.customers',

    config: {
        refs: {
            newCustomerBtn: 'button#newCustomerBtn',
            newCustomerView: {
                selector: '#newcustomer',
                xtype: 'newcustomer'
            },
            customersNav: {
                selector: 'customersnav',
                xtype: 'Ext.navigation.Bar'
            }
        },

        control: {
            "#newCustomerBtn": {
                tap: 'onNewCustomerTap'
            },
            "navigationview": {
                activeitemchange: 'onNavigationviewActiveItemChange'
            }
        }
    },

    onNewCustomerTap: function(button, e, eOpts) {
        navView = Ext.ComponentQuery.query('customersnav')[0];
        navView.push({
                        xtype: 'newcustomer',
                        title: 'Nuevo Cliente'
                    });

    },

    onNavigationviewActiveItemChange: function(container, value, oldValue, eOpts) {
        var btn = this.getNewCustomerBtn();
        if (value.id == 'customers') {
          btn.show();
        } else {
          btn.hide();
        }
    }

});